version: '1'
services:

  rest-service:
    image: frankawesome/tuncrest-11:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    hostname: rest-service

  node:
    image: frankawesome/tuncnode-11:latest
    networks:
      - app-network

  tuncdb:
    image: frankawesome/tuncdb-3:latest
    networks:
      - app-network

networks:
  app-network:
